baseurl = "https://murshidazher.com/"
theme="murshid-starter"
languageCode = "en"
title = "Murshid Azher"
pluralizelisttitles = false

# Enable for syntax highlighting
pygmentsUseClasses=true
# Enable highlighting for code fences
pygmentsCodeFences = true
# pygmentsCodefencesGuessSyntax = true

disableHugoGeneratorInject = true
enableRobotsTXT = true
canonifyURLs = true

# Enable for getting last mod date from Github
enableGitInfo = true

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 1


[params]
  keywords = "Product Design, UX Design, UI Design, Front-end, Web Development, Visual Identity, Back-end, Software, Small businesses, Murshid Azher, Murshid, Azher, Automation, Typography, Software Engineer, Developer"
  description = "Murshid Azher is a professional designer and software developer from Colombo, Sri Lanka. Read technical articles and notes on coding, designing and much more."
  strapline = "Coder, Designer, and Data Enthusiast"
  location = "Colombo, LK"

  # Set Cloudinary URL for image hosting
  cloudinary_url = "https://res.cloudinary.com/murshidazher/image/upload"
  author = "Murshid Azher"

[author]
  name = "Murshid Azher"
  email = "hello@murshidazher.com"
  twitter = "https://twitter.com/murshidazher"
  github = "https://github.com/murshidazher"
  linkedin = "https://linkedin.com/in/murshidazher"
  dribbble = "https://dribbble.com/murshidazher"
  instagram = "https://www.instagram.com/murshidazher"
  behance = "https://www.behance.net/murshidazher"

[taxonomies]
  tag = "tags"

[outputs]
  home = [ "HTML", "RSS" ]

[markup.goldmark.renderer]
  unsafe = true

[outputFormats]
[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "feed"

[permalinks]
  projects = "/:section/:slug/"
  notes = "/:section/:slug/"
  page = "/:title/"

# Enable Emojis
enableEmoji = true

[[menu.main]]
  name = "Articles"
  url = "/articles/"
  pre = "📝"
  weight = 5

[[menu.main]]
  name = "Notes"
  pre = "📚"
  url = "/notes/"
  weight = 10

[[menu.main]]
  name = "Tags"
  pre = "🔖"
  url = "/tags/"
  weight = 15


[[menu.footer]]
  name = "Articles"
  url = "/articles/"
  weight = 5

[[menu.footer]]
  name = "Notes"
  url = "/notes/"
  weight = 10

[[menu.footer]]
  name = "Tags"
  url = "/tags/"
  weight = 15
