name = "Murshid Starter"
license = "MIT"
licenselink = "Link to theme's license"
description = "Theme description"
homepage = "Link of your theme"
tags = ["blog", "portfolio"]
features = ["lightning", "fast", "hugo"]
min_version = "0.41.0"

[author]
  name = "Your name"
  homepage = "Your website"

# If porting an existing theme
[original]
  name = "Murshid Azher"
  homepage = ""
  repo = "Link to source code of original theme"
